language: rust
sudo: "required"
dist: trusty
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email: false
  slack: way-cooler:bf5hNqMVmTgFpHo3a3vgZ4Lu
before_install:
  - sudo add-apt-repository -y ppa:wayland.admin/daily-builds
  - sudo apt-get update -qq
  - sudo apt-get install -y libwayland-dev libwayland-protocols-dev libegl1-mesa-dev libgles2-mesa-dev udev asciidoc
before_script:
  -  which rustfmt || cargo install rustfmt
script:
  # wlroots-rs
  - cargo build --verbose
  - cargo build --verbose --features="static wlroots-sys"
  - cargo doc
  - cargo fmt -- --write-mode=diff

  - cd wlroots-sys
  - cargo build --verbose
  - cargo build --verbose --features="static"
  - cargo doc
