[workspace]
members = ["wlroots-sys", "wlroots-dehandle"]

[package]
name = "wlroots"
version = "0.0.0"
authors = ["Timidger <APragmaticPlace@gmail.com>"]
description = "Rust wrapping for Wayland compositor library wlroots"
keywords = ["wayland", "compositor", "bindings"]
categories = ["external-ffi-bindings", "gui"]
license = "MIT"
exclude = [".travis.yml"]

[badges]
travis-ci = { repository = "way-cooler/wlroots-rs/" }


[dependencies]
libc = "^0.2.*"
rust-ini = "0.10.0"
wlroots-sys = { path = "wlroots-sys", default-features = false }
wlroots-dehandle = { path = "wlroots-dehandle" }
wayland-sys = { version = "0.21.*", features = ["client", "dlopen", "server",] }
lazy_static = "0.2"
xkbcommon = "0.3"
bitflags = "1.0"
vsprintf = "1.0.1"

[dev-dependencies]
wayland-client = { version = "0.21.*", features = ["native_lib"] }
byteorder = "1"
tempfile = "2"

[features]
default = ["static", "libcap", "systemd", "elogind", "unstable-features"]
static = ["wlroots-sys/static"]
libcap = ["wlroots-sys/libcap"]
systemd = ["wlroots-sys/systemd"]
elogind = ["wlroots-sys/elogind"]
unstable-features = ["wlroots-sys/unstable-features"]
