[workspace]
members = ["wlroots-sys", "rootston", "example-config"]

[package]
name = "wlroots"
version = "0.0.0"
authors = ["Timidger <APragmaticPlace@gmail.com>"]
description = "Rust wrapping for Wayland compositor library wlroots"
keywords = ["wayland", "compositor", "bindings"]
categories = ["external-ffi-bindings", "gui"]
license = "MIT"
exclude = [".travis.yml"]

build = "build.rs"

[badges]
travis-ci = { repository = "way-cooler/wlroots-rs/" }


[dependencies]
libc = "^0.2.*"
rust-ini = "0.10.0"
wlroots-sys = { path = "wlroots-sys" }
wayland-sys = { version = "0.9.*", features = ["client", "dlopen", "server",] }
lazy_static = "0.2"
xkbcommon = "0.3"
bitflags = "1.0"

[build-dependencies]
gl_generator = "0.5.0"

[features]
default = ["static"]
static = ["wlroots-sys/static"]
